title: RubyVE
name: RubyVE
tagline: Grupo de Usuarios Ruby de Venezuela

connect:
  twitter: https://twitter.com/rubyve
  gplus: https://plus.google.com/communities/106213524853304399957
  ggoogle: https://groups.google.com/forum/#!forum/rubyve
  github: https://github.com/ruby-ve
  irc: irc://irc.freenode.net/#rubyve

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CC-LICENSE
  - LAYON-LICENSE

markdown: redcarpet
highlighter: rouge

permalink: pretty

host: 0.0.0.0
port: 3000
baseurl: /
url: http://ruby.org.ve
lsi: false

gems:
  - jekyll-sitemap

prose:
  rooturl: '_posts'
  siteurl: 'https://ruby-ve.github.io/'
  media: 'assets'
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
          placeholder: "John Doe"
          type: "text"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "Add a post description under 155 characters."
          type: "text"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Post Category"
          placeholder: "Create or choose"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
